### ISSUE TITLE
i see tslib in bundle. is it required in runtime?

### ISSUE THREAD

**Issue by garyxuehong** [glixlur/jsx-dom#8]
i see tslib in bundle. is it required in runtime?

If it is not required in runtime, maybe I configured in correctly.

Thanks

**Comment by glixlur** [comment]
Yes, but only for the `__assign` function. The expectation is that your build tool will automatically strip away the other unused functions because it is an ES2015 import.

You can always replace it with native `Object.assign` if you wish.

**Comment by garyxuehong** [comment]
hi thanks, how can I replace it with Object.assign?
I use `import {h} from 'jsx-dom'`, which is `createElement` anyway, it internally use __assign from tslib. That's why rollup doesn't shaking if off.
so anyway i can use Object.assign instead?

**Comment by glixlur** [comment]
Yes, you can. Replace `import { __assign } from 'tslib'` with `const __assign = Object.assign` and you should be good to go.

Currently this function is kept for compatibility with an ancient browser from Microsoft.

**Comment by garyxuehong** [comment]
Do you mean I need to modify the files in node_modules folder?
Alex <notifications@github.com>于2018年4月7日 周六下午12:34写道：

**Comment by glixlur** [comment]
If you wish to remove it, yes. The function is only a few lines so I don’t think it’s worth the effort.

**Comment by proteria** [comment]
It is no longer a dependency.
