### ISSUE TITLE
Master branch doesn't match the NPM package

### ISSUE THREAD

**Issue by naftis** [glixlur/jsx-dom#9]
![image](https://user-images.githubusercontent.com/1322608/48318344-e40cbe00-e607-11e8-96b6-e2c651051e94.png)

https://www.npmjs.com/package/jsx-dom
I think this isn't the same version?

**Comment by glixlur** [comment]
Thanks for reporting. I’ll fix this once my computer is back from repair.

**Comment by glixlur** [comment]
Fixed.
